# 開發環境專用的 Docker Compose 配置
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mermaid-render-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: mermaid_render_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - mermaid-dev-network

  redis:
    image: redis:7-alpine
    container_name: mermaid-render-cache-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - mermaid-dev-network
    command: redis-server --appendonly yes

  # 開發環境只需要資料庫和快取服務
  # 前後端應用直接在本機運行以支援熱重載

networks:
  mermaid-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local
