version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15-alpine
    container_name: mermaid-render-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mermaid_render
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mermaid-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis 快取
  redis:
    image: redis:7-alpine
    container_name: mermaid-render-cache
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - mermaid-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  # 後端 API 服務
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mermaid-render-api
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mermaid_render
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret-change-in-production
      PORT: 3001
      HOST: 0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mermaid-network
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # 前端應用服務
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mermaid-render-web
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://localhost:3001/api
      NEXT_PUBLIC_APP_ENV: development
    depends_on:
      - backend
    networks:
      - mermaid-network
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/.next
      - /app/node_modules

networks:
  mermaid-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
